name: ğŸš€ Build Flutter APK & App Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: ğŸ”§ Build Flutter
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ’» Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: ğŸ“¦ Get dependencies
        run: flutter pub get

      - name: ğŸ— Build APK
        run: flutter build apk --release

      - name: ğŸ— Build App Bundle (AAB)
        run: flutter build appbundle --release

      - name: ğŸ“‚ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ByteChat-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: ğŸ“‚ Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: ByteChat-release.aab
          path: build/app/outputs/bundle/release/app-release.aab